export const ADD_PRODUCTS= 'ADD_INGREDIENT';
export const REMOVE_PRODUCTS= 'REMOVE_INGREDIENT';
export const SET_PRODUCTS = 'SET_INGREDIENTS';
export const FETCH_PRODUCTS_FAILED = 'FETCH_INGREDIENTS_FAILED';
